from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageBreak,
    PageTemplate,
    Paragraph,
    Preformatted,
    Spacer,
    Table,
    TableStyle,
)


OUTPUT = "output/pdf/bookmytable-backend-interview-explanation.pdf"


def page_chrome(canvas, doc):
    canvas.saveState()
    width, height = A4
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(colors.HexColor("#111827"))
    canvas.drawString(0.62 * inch, height - 0.42 * inch, "BookMyTable Backend Interview Notes")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#6B7280"))
    canvas.drawRightString(width - 0.62 * inch, 0.36 * inch, f"Page {doc.page}")
    canvas.restoreState()


def p(text, style):
    return Paragraph(text, style)


def b(text, style):
    return Paragraph("- " + text, style)


def file_block(story, styles, file_name, role, explain, flow=None, code=None, interview=None):
    story.append(p(file_name, styles["file"]))
    story.append(p("<b>Role:</b> " + role, styles["body"]))
    story.append(p("<b>Simple explanation:</b> " + explain, styles["body"]))
    if flow:
        story.append(p("Execution / logic order", styles["h3"]))
        for item in flow:
            story.append(b(item, styles["body"]))
    if code:
        story.append(Preformatted(code, styles["code"]))
    if interview:
        story.append(p("Interview answer", styles["h3"]))
        story.append(p(interview, styles["callout"]))
    story.append(Spacer(1, 8))


def endpoint_table(styles):
    rows = [
        ["Method", "Endpoint", "Controller", "Purpose"],
        ["GET", "/api/health", "server.js", "Checks whether backend is running."],
        ["POST", "/api/bookings", "createBooking", "Creates a new reservation."],
        ["GET", "/api/bookings", "getAllBookings", "Returns all bookings for admin dashboard."],
        ["GET", "/api/bookings/available-slots?date=...", "getAvailableSlots", "Returns only free time slots for a date."],
        ["GET", "/api/bookings/analytics", "getAnalytics", "Returns peak hours, popular cuisines, and total bookings."],
        ["GET", "/api/bookings/:id", "getBookingById", "Finds booking by public bookingId."],
        ["DELETE", "/api/bookings/:id", "deleteBooking", "Deletes booking by public bookingId."],
        ["GET", "/api/weather?date=...&location=...", "fetchWeather", "Returns weather forecast for booking support."],
    ]
    table = Table(rows, colWidths=[0.62 * inch, 2.25 * inch, 1.45 * inch, 2.2 * inch], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7.5),
                ("LEADING", (0, 0), (-1, -1), 9.5),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#CBD5E1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def qa_table(styles):
    rows = [
        ["Question", "Answer to give"],
        ["What starts the backend?", "npm run dev runs nodemon server.js, or npm start runs node server.js."],
        ["Why type: module?", "It allows ES module import/export syntax instead of CommonJS require/module.exports."],
        ["Why recreate __dirname?", "In ES modules, __dirname is not available by default, so fileURLToPath and path.dirname recreate it."],
        ["How is MongoDB connected?", "server.js calls connectDB(), which reads MONGODB_URI and connects using mongoose.connect()."],
        ["How do routes reach controllers?", "server.js mounts /api, routes/index.js mounts /bookings and /weather, then route files call controller functions."],
        ["How do you prevent double booking?", "createBooking checks for an existing confirmed booking with the same normalized date and trimmed time."],
        ["Why normalize date to midnight?", "So the same calendar date compares consistently in MongoDB regardless of time component."],
        ["What is bookingId?", "A UUID generated by uuidv4; it is public and separate from MongoDB's internal _id."],
        ["How does availability work?", "It starts from a fixed list of slots, fetches confirmed bookings for the date, and removes taken slots."],
        ["How is weather used?", "The backend gets forecast data from OpenWeatherMap and stores it in weatherInfo for seating or booking context."],
        ["Is email real production email?", "No. It uses Ethereal test SMTP, useful for development preview links. Production would use a real SMTP provider."],
        ["Any security limitation?", "Admin booking and analytics routes currently have no authentication; in production, JWT/session auth should protect them."],
    ]
    table = Table(rows, colWidths=[2.15 * inch, 4.35 * inch], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F766E")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7.7),
                ("LEADING", (0, 0), (-1, -1), 9.8),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#CBD5E1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def build():
    sample = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "title",
            parent=sample["Title"],
            fontName="Helvetica-Bold",
            fontSize=21,
            leading=26,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#111827"),
            spaceAfter=6,
        ),
        "sub": ParagraphStyle(
            "sub",
            parent=sample["Normal"],
            fontSize=9.5,
            leading=13,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#4B5563"),
            spaceAfter=14,
        ),
        "h2": ParagraphStyle(
            "h2",
            parent=sample["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#111827"),
            spaceBefore=10,
            spaceAfter=5,
        ),
        "h3": ParagraphStyle(
            "h3",
            parent=sample["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=9.5,
            leading=12,
            textColor=colors.HexColor("#334155"),
            spaceBefore=5,
            spaceAfter=3,
        ),
        "file": ParagraphStyle(
            "file",
            parent=sample["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12.5,
            leading=16,
            textColor=colors.HexColor("#075985"),
            backColor=colors.HexColor("#E0F2FE"),
            borderColor=colors.HexColor("#38BDF8"),
            borderWidth=0.5,
            borderPadding=5,
            spaceBefore=9,
            spaceAfter=5,
        ),
        "body": ParagraphStyle(
            "body",
            parent=sample["BodyText"],
            fontSize=9.2,
            leading=12.4,
            textColor=colors.HexColor("#1F2937"),
            spaceAfter=4,
        ),
        "callout": ParagraphStyle(
            "callout",
            parent=sample["BodyText"],
            fontSize=9,
            leading=12.2,
            textColor=colors.HexColor("#0F172A"),
            backColor=colors.HexColor("#ECFDF5"),
            borderColor=colors.HexColor("#34D399"),
            borderWidth=0.5,
            borderPadding=6,
            spaceAfter=6,
        ),
        "warn": ParagraphStyle(
            "warn",
            parent=sample["BodyText"],
            fontSize=9,
            leading=12.2,
            textColor=colors.HexColor("#451A03"),
            backColor=colors.HexColor("#FEF3C7"),
            borderColor=colors.HexColor("#F59E0B"),
            borderWidth=0.5,
            borderPadding=6,
            spaceAfter=6,
        ),
        "code": ParagraphStyle(
            "code",
            fontName="Courier",
            fontSize=7.5,
            leading=9.5,
            textColor=colors.HexColor("#111827"),
            backColor=colors.HexColor("#F3F4F6"),
            borderColor=colors.HexColor("#CBD5E1"),
            borderWidth=0.4,
            borderPadding=5,
            leftIndent=4,
            rightIndent=4,
            spaceBefore=3,
            spaceAfter=6,
        ),
    }

    doc = BaseDocTemplate(
        OUTPUT,
        pagesize=A4,
        leftMargin=0.62 * inch,
        rightMargin=0.62 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.58 * inch,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="normal")
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=page_chrome)])

    story = []
    story.append(p("BookMyTable Backend Explanation", styles["title"]))
    story.append(p("Simple interview notes, ordered by execution hierarchy", styles["sub"]))
    story.append(
        p(
            "Read this from top to bottom. It follows how the backend starts, receives a request, "
            "routes it, runs business logic, and stores data in MongoDB.",
            styles["body"],
        )
    )

    story.append(p("Backend Execution Hierarchy", styles["h2"]))
    hierarchy = [
        "backend/package.json defines scripts: npm start and npm run dev.",
        "backend/server.js starts Express, middleware, database connection, routes, error handler, and listening port.",
        "backend/config/db.js connects to MongoDB using MONGODB_URI.",
        "backend/routes/index.js combines route groups under /bookings and /weather.",
        "backend/routes/booking.route.js maps booking URLs to controller functions.",
        "backend/routes/weather.route.js maps weather URL to fetchWeather.",
        "backend/controllers/booking.controller.js contains main business logic.",
        "backend/config/weather.js calls OpenWeatherMap and returns clean weather data.",
        "backend/models/booking.model.js defines the MongoDB Booking schema.",
        "backend/.env stores configuration values. backend/package-lock.json locks dependency versions.",
    ]
    for item in hierarchy:
        story.append(b(item, styles["body"]))

    story.append(p("API Endpoint Map", styles["h2"]))
    story.append(endpoint_table(styles))

    file_block(
        story,
        styles,
        "1. backend/package.json",
        "Defines backend metadata, npm scripts, module style, dependencies, and dev dependencies.",
        "When you run the backend, this file tells Node which command to execute. The project uses ES modules because type is module.",
        flow=[
            "npm start -> node server.js for normal execution.",
            "npm run dev -> nodemon server.js for development auto-restart.",
            "main: server.js tells the package that server.js is the main backend file.",
            "dependencies are runtime packages used by the backend.",
        ],
        code='"scripts": {\n  "start": "node server.js",\n  "dev": "nodemon server.js"\n},\n"type": "module"',
        interview="I can explain that package.json is not business logic, but it is the starting configuration. It defines how the backend is launched and which libraries the server depends on.",
    )

    file_block(
        story,
        styles,
        "2. backend/server.js",
        "Main backend entry file. This is the first code file to explain in execution flow.",
        "It loads environment variables, creates the Express app, enables middleware, connects to MongoDB, mounts routes under /api, adds a global error handler, and starts listening on the port.",
        flow=[
            "Imports Express, CORS, dotenv, path helpers, connectDB, and routes.",
            "Creates __filename and __dirname because ES modules do not provide them automatically.",
            "Loads backend/.env using dotenv.config().",
            "Creates app with express() and chooses PORT from process.env.PORT or 8082.",
            "Adds cors() so frontend can call backend from another port.",
            "Adds express.json() so JSON request bodies become req.body.",
            "Defines GET /api/health for quick server checking.",
            "Calls connectDB() to connect MongoDB.",
            "Mounts all imported routes at /api.",
            "Adds global error handler, then starts server with app.listen().",
        ],
        code='app.use(cors());\napp.use(express.json());\napp.get("/api/health", ...);\nconnectDB();\napp.use("/api", routes);\napp.listen(PORT, ...);',
        interview="server.js is the bootstrap file. Every frontend API request enters through this Express server first, passes through middleware, then reaches the route and controller layers.",
    )

    file_block(
        story,
        styles,
        "3. backend/config/db.js",
        "Connects the backend to MongoDB through Mongoose.",
        "It reads MONGODB_URI from environment variables. If the URI is missing or connection fails, the server logs the problem and exits instead of running with a broken database.",
        flow=[
            "Reads process.env.MONGODB_URI.",
            "If missing, logs an error and calls process.exit(1).",
            "If present, calls mongoose.connect(uri).",
            "Logs success after connection.",
            "Exports connectDB for server.js.",
        ],
        code="const uri = process.env.MONGODB_URI;\nconst conn = await mongoose.connect(uri);",
        interview="Mongoose is used as the ODM. It provides schema-based modeling and methods like findOne, find, save, aggregate, and countDocuments.",
    )

    file_block(
        story,
        styles,
        "4. backend/routes/index.js",
        "Main router that combines smaller route files.",
        "This file keeps server.js clean. Instead of importing every route group into server.js, it imports booking routes and weather routes here, then exports one combined router.",
        flow=[
            "Creates an Express router.",
            "Mounts bookingRoutes at /bookings.",
            "Mounts weatherRoutes at /weather.",
            "Exports router to server.js.",
        ],
        code='router.use("/bookings", bookingRoutes);\nrouter.use("/weather", weatherRoutes);',
        interview="Because server.js mounts this router at /api, the final paths become /api/bookings and /api/weather.",
    )

    file_block(
        story,
        styles,
        "5. backend/routes/booking.route.js",
        "Defines booking-related API URLs and connects them to controller functions.",
        "This route file does not contain business logic. It only maps HTTP method plus URL to the correct controller.",
        flow=[
            "POST /api/bookings calls createBooking.",
            "GET /api/bookings calls getAllBookings.",
            "GET /api/bookings/available-slots calls getAvailableSlots.",
            "GET /api/bookings/analytics calls getAnalytics.",
            "GET /api/bookings/:id calls getBookingById.",
            "DELETE /api/bookings/:id calls deleteBooking.",
        ],
        code='router.post("/", createBooking);\nrouter.get("/", getAllBookings);\nrouter.get("/available-slots", getAvailableSlots);\nrouter.get("/analytics", getAnalytics);\nrouter.get("/:id", getBookingById);\nrouter.delete("/:id", deleteBooking);',
        interview="Routes are separated from controllers to keep the code organized. Routes decide what function runs; controllers decide what actually happens.",
    )

    file_block(
        story,
        styles,
        "6. backend/routes/weather.route.js",
        "Defines the weather API route.",
        "It maps GET /api/weather to fetchWeather from booking.controller.js. This is a small route file because weather logic is handled in the controller and config/weather.js.",
        flow=[
            "Creates Express router.",
            "GET / maps to fetchWeather.",
            "Because of parent routers, final URL is /api/weather.",
        ],
        code='router.get("/", fetchWeather);',
        interview="The weather route lets frontend request weather by query params like date and location without directly calling OpenWeatherMap from the browser.",
    )

    story.append(PageBreak())
    story.append(p("7. backend/controllers/booking.controller.js", styles["file"]))
    story.append(
        p(
            "<b>Role:</b> This is the main business logic file. It creates bookings, checks slot conflicts, sends test emails, fetches availability, returns admin data, deletes bookings, fetches weather, and computes analytics.",
            styles["body"],
        )
    )
    story.append(p("Top-level setup", styles["h3"]))
    for item in [
        "Imports uuidv4 to create a public unique bookingId.",
        "Imports getWeatherForDate from config/weather.js.",
        "Imports nodemailer for email confirmation.",
        "Imports Booking model for MongoDB operations.",
        "Creates a module-level transporter variable for email.",
    ]:
        story.append(b(item, styles["body"]))

    story.append(p("initEmail()", styles["h3"]))
    for item in [
        "Creates an Ethereal test email account.",
        "Builds a nodemailer transporter using smtp.ethereal.email.",
        "Runs once when the controller file is imported.",
        "Important: Ethereal is for development/testing, not real production customer email.",
    ]:
        story.append(b(item, styles["body"]))
    story.append(Preformatted("let transporter;\nconst initEmail = async () => { ... };\ninitEmail();", styles["code"]))

    story.append(p("sendConfirmationEmail(booking)", styles["h3"]))
    for item in [
        "Returns early if transporter is not ready.",
        "Builds email content using booking email, guests, date, and time.",
        "Sends email through nodemailer.",
        "Logs Ethereal preview URL so developer can view the test email.",
    ]:
        story.append(b(item, styles["body"]))
    story.append(
        p(
            "Interview note: If asked why EMAIL_USER and EMAIL_PASS are in .env but not used here, say the current code uses Ethereal test accounts. For production, those env values could be used to configure a real SMTP provider.",
            styles["warn"],
        )
    )

    story.append(p("createBooking(req, res)", styles["h3"]))
    for item in [
        "Reads customerEmail, bookingDate, bookingTime, numberOfGuests, and other fields from req.body.",
        "Normalizes bookingDate to midnight using setHours(0,0,0,0).",
        "Checks Booking.findOne for same date, same trimmed time, and status confirmed.",
        "If a booking already exists, returns 400 with This slot is already taken.",
        "Calls getWeatherForDate(bookingDate, Mumbai) and stores the returned weatherInfo.",
        "Creates a new Booking with uuid bookingId, Guest as default customerName, confirmed status, and other request data.",
        "Saves it with newBooking.save().",
        "If email looks valid, sends confirmation email.",
        "Returns 201 with the saved booking.",
    ]:
        story.append(b(item, styles["body"]))
    story.append(
        Preformatted(
            'const exists = await Booking.findOne({\n'
            "  bookingDate: targetDate,\n"
            "  bookingTime: bookingTime.trim(),\n"
            '  status: "confirmed",\n'
            "});",
            styles["code"],
        )
    )
    story.append(
        p(
            "Interview answer: This function is the core reservation flow. It validates slot uniqueness, enriches the booking with weather, saves the booking, optionally sends email, and returns the created record.",
            styles["callout"],
        )
    )

    story.append(p("getAvailableSlots(req, res)", styles["h3"]))
    for item in [
        "Reads date from req.query.",
        "Defines a fixed list of allowed restaurant time slots.",
        "Normalizes the requested date.",
        "Finds confirmed bookings for that date and selects only bookingTime.",
        "Removes taken slots from the fixed slot list.",
        "Returns the remaining available slots.",
    ]:
        story.append(b(item, styles["body"]))

    story.append(p("getAllBookings(req, res)", styles["h3"]))
    for item in [
        "Fetches all bookings from MongoDB.",
        "Sorts by createdAt descending, so newest bookings appear first.",
        "Used by the admin dashboard list.",
    ]:
        story.append(b(item, styles["body"]))

    story.append(p("getBookingById(req, res)", styles["h3"]))
    for item in [
        "Reads id from URL params.",
        "Searches by bookingId, not MongoDB _id.",
        "Returns 404 if missing.",
        "Returns booking data if found.",
    ]:
        story.append(b(item, styles["body"]))

    story.append(p("deleteBooking(req, res)", styles["h3"]))
    for item in [
        "Reads id from URL params.",
        "Deletes the document whose bookingId matches id.",
        "Returns 404 if no booking is found.",
        "Returns success message after deletion.",
    ]:
        story.append(b(item, styles["body"]))

    story.append(p("fetchWeather(req, res)", styles["h3"]))
    for item in [
        "Reads date and location from query params.",
        "Calls getWeatherForDate(date, location).",
        "Returns weather JSON to frontend.",
    ]:
        story.append(b(item, styles["body"]))

    story.append(p("getAnalytics(req, res)", styles["h3"]))
    for item in [
        "Uses Booking.aggregate to group bookings by bookingTime and count peak hours.",
        "Uses Booking.aggregate to group bookings by cuisinePreference and count popular cuisines.",
        "Uses countDocuments to get total bookings.",
        "Returns peakHours, popularCuisines, totalBookings, topCuisine, and topHour.",
    ]:
        story.append(b(item, styles["body"]))
    story.append(
        Preformatted(
            'Booking.aggregate([\n'
            '  { $group: { _id: "$bookingTime", count: { $sum: 1 } } },\n'
            "  { $sort: { count: -1 } },\n"
            "]);",
            styles["code"],
        )
    )

    story.append(p("8. backend/config/weather.js", styles["file"]))
    story.append(
        p(
            "<b>Role:</b> Handles weather integration with OpenWeatherMap. It keeps external API logic separate from controller logic.",
            styles["body"],
        )
    )
    for item in [
        "Reads OPEN_WEATHER_API_KEY from environment variables.",
        "If API key is missing, returns Unknown/Unavailable instead of crashing.",
        "Calls OpenWeather geocoding API to convert city into latitude and longitude.",
        "Calls OpenWeather 5-day forecast API using those coordinates.",
        "Finds the forecast entry matching the requested booking date.",
        "If exact date is not found, falls back to the first forecast item.",
        "Returns only temperature, condition, and description.",
    ]:
        story.append(b(item, styles["body"]))
    story.append(
        p(
            "Interview note: OpenWeather's 5-day forecast cannot reliably answer dates far in the future. This code handles that by using fallback data, but in production you may restrict booking dates or use another forecast source.",
            styles["warn"],
        )
    )

    file_block(
        story,
        styles,
        "9. backend/models/booking.model.js",
        "Defines the Booking schema and exports the Mongoose model.",
        "This file controls the shape, validation rules, defaults, and timestamps for booking documents in MongoDB.",
        flow=[
            "bookingId is required and unique. It comes from uuidv4.",
            "customerName is required and trimmed. Controller currently defaults it to Guest.",
            "customerEmail is trimmed and lowercased.",
            "numberOfGuests is required and must be at least 1.",
            "bookingDate and bookingTime are required.",
            "cuisinePreference and specialRequests are optional trimmed strings.",
            "weatherInfo stores weather JSON and defaults to empty object.",
            "seatingPreference is enum: indoor or outdoor, default indoor.",
            "status is enum: confirmed, pending, cancelled, default confirmed.",
            "timestamps creates createdAt and updatedAt automatically.",
        ],
        code='const Booking = mongoose.model("Booking", bookingSchema);\nexport default Booking;',
        interview="The model is important because it enforces data structure at the database layer. Controllers use this model for save, find, delete, aggregate, and count operations.",
    )

    story.append(p("10. backend/.env", styles["file"]))
    story.append(
        p(
            "<b>Role:</b> Stores configuration and secrets outside source code. Do not commit real secrets in public repositories.",
            styles["body"],
        )
    )
    for item in [
        "MONGODB_URI: database connection string used by config/db.js.",
        "OPEN_WEATHER_API_KEY: API key used by config/weather.js.",
        "PORT: backend port used by server.js.",
        "EMAIL_USER and EMAIL_PASS: present in .env, but current email implementation uses Ethereal test accounts instead.",
    ]:
        story.append(b(item, styles["body"]))

    story.append(p("11. backend/package-lock.json and .gitignore", styles["file"]))
    for item in [
        "package-lock.json locks exact dependency versions so installs are repeatable.",
        ".gitignore should prevent node_modules and secret files like .env from being committed.",
        "node_modules is generated by npm install and should not be explained line by line in interviews.",
    ]:
        story.append(b(item, styles["body"]))

    story.append(PageBreak())
    story.append(p("Complete Request Flow To Speak", styles["h2"]))
    story.append(
        p(
            "When the user creates a booking from the frontend, the request goes to POST /api/bookings. "
            "server.js receives it, CORS and JSON middleware run, routes/index.js forwards /bookings to "
            "booking.route.js, and booking.route.js calls createBooking. The controller normalizes the date, "
            "checks if the same confirmed date and time already exists, fetches weather, creates a Booking "
            "document with a UUID bookingId, saves it in MongoDB, sends a test confirmation email if possible, "
            "and returns the saved booking as JSON.",
            styles["callout"],
        )
    )

    story.append(p("Important Limitations To Be Honest About", styles["h2"]))
    limitations = [
        "No authentication is currently protecting admin booking list, delete, or analytics endpoints. Production should add auth.",
        "Input validation is basic. Production should validate required fields, date format, email format, and allowed slots before saving.",
        "Slot conflict checking prevents same date/time double booking, but it does not consider table count or restaurant capacity.",
        "Email uses Ethereal test email, so it is good for development but not real customer delivery.",
        "Weather API supports only near-term forecast. Far future booking dates may use fallback weather data.",
        "Controllers often return res.status(500) directly, so the global error handler exists but is not heavily used with next(error).",
        "No automated tests are defined yet; package.json test script is still a placeholder.",
    ]
    for item in limitations:
        story.append(b(item, styles["body"]))

    story.append(p("Interview Questions And Short Answers", styles["h2"]))
    story.append(qa_table(styles))

    story.append(p("Final 60-Second Backend Explanation", styles["h2"]))
    story.append(
        p(
            "The backend is a Node.js and Express API using MongoDB through Mongoose. Execution starts from "
            "package.json scripts, which run server.js. server.js loads environment variables, creates the Express "
            "app, enables CORS and JSON parsing, connects to MongoDB, mounts all API routes under /api, and starts "
            "listening. The main router splits requests into booking and weather routes. Booking routes call controller "
            "functions, where the core logic lives: creating bookings, checking slot conflicts, getting available slots, "
            "listing and deleting bookings, fetching weather, sending test emails, and generating analytics. The Booking "
            "model defines the MongoDB schema and validation rules. Configuration like MongoDB URI, weather API key, and "
            "port comes from .env.",
            styles["callout"],
        )
    )

    doc.build(story)


if __name__ == "__main__":
    build()
